name: chinese_learning
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_splash_screen: null
  audioplayers: ^0.20.1
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.4.0
  flutter_secure_storage: ^4.2.1
  http: ^0.13.4
  intl: ^0.17.0
  json_serializable: ^6.1.5
  native_notify: ^0.0.12
  provider: ^6.0.4
  smooth_page_indicator: ^0.3.0-nullsafety.0
  speech_to_text: ^5.4.3
  url_launcher: ^6.0.20
  url_launcher_web: ^2.0.9

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/fyp_logo.png"

flutter:
  assets:
    - lib/assets/images/handa_img/image2.jpg
    - lib/assets/images/handa_img/image5.jpg
    - lib/assets/images/handa_img/
    - lib/assets/contactsLogo.png
    - lib/assets/importance.jpg
    - lib/assets/logoutLogo.png
    - lib/assets/learnmore.png
    - lib/assets/fyp_logo_white.png
    - lib/assets/about.png
    - lib/assets/test.png
    - lib/assets/learn.png
    - lib/assets/client.png
    - lib/assets/dictionary2.png
    - lib/assets/logout.png
    - lib/assets/translate.png
    - lib/assets/feedback.png
    - lib/assets/feedbackwithoutbackground.png
    - lib/assets/audio/test.mp3
    - lib/assets/audio/
    - lib/assets/
  uses-material-design: true

  fonts:
    - family: Bitter
      fonts:
        - asset: lib/assets/fonts/Bitter-Regular.ttf
        - asset: lib/assets/fonts/Bitter-Medium.ttf
          style: normal
        - asset: lib/assets/fonts/Bitter-SemiBold.ttf
          weight: 200
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
